// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBolROK5SDgRi6kwDlieYMexEzn02OnwlM',
    appId: '1:943675604857:web:81895ee834180a06e839a8',
    messagingSenderId: '943675604857',
    projectId: 'road-sewa',
    authDomain: 'road-sewa.firebaseapp.com',
    storageBucket: 'road-sewa.firebasestorage.app',
    measurementId: 'G-JFMG8J2B93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS_cruwEcCXJm6YCL3DNObysfqb1unhzs',
    appId: '1:943675604857:android:0e6c905e89d53c6ae839a8',
    messagingSenderId: '943675604857',
    projectId: 'road-sewa',
    storageBucket: 'road-sewa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAipff-l1xNF-PioiQApxo9CFs99mhB_vM',
    appId: '1:943675604857:ios:12107b829e92490fe839a8',
    messagingSenderId: '943675604857',
    projectId: 'road-sewa',
    storageBucket: 'road-sewa.firebasestorage.app',
    iosBundleId: 'com.example.apiCallWithRetrofit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAipff-l1xNF-PioiQApxo9CFs99mhB_vM',
    appId: '1:943675604857:ios:12107b829e92490fe839a8',
    messagingSenderId: '943675604857',
    projectId: 'road-sewa',
    storageBucket: 'road-sewa.firebasestorage.app',
    iosBundleId: 'com.example.apiCallWithRetrofit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBolROK5SDgRi6kwDlieYMexEzn02OnwlM',
    appId: '1:943675604857:web:ea08ac9db9579201e839a8',
    messagingSenderId: '943675604857',
    projectId: 'road-sewa',
    authDomain: 'road-sewa.firebaseapp.com',
    storageBucket: 'road-sewa.firebasestorage.app',
    measurementId: 'G-6SYZ421HSS',
  );
}
